In [1]:
import numpy as np

In [2]:
arr=np.array([3,1,2])
arr.shape

(3,)

In [3]:
mat1=np.ones((3,4))
mat2=np.zeros((3,4))

In [6]:
np.savez('file_.npz',mat_one=mat1,mat_zero=mat2)

In [7]:
with np.load('file_.npz') as file:
    mat1=file['mat_one']
    mat2=file['mat_zero']

In [8]:
m1 = np.array([[1,2,3],
[0,0,0]])
m2 = np.array([[4,5,6],
[1,1,1]])




The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


In [9]:


new_mat = np.hstack((m1, m2))
new_mat

array([[1, 2, 3, 4, 5, 6],
       [0, 0, 0, 1, 1, 1]])

In [10]:


new_mat = np.vstack((m1, m2))
new_mat

array([[1, 2, 3],
       [0, 0, 0],
       [4, 5, 6],
       [1, 1, 1]])

In [ ]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])
np.isclose(v1,v2, atol= 2)

array([ True,  True,  True,  True,  True])

In [17]:
np.allclose(v1,v2, atol= 3)

True

In [19]:
V = np.array ([2,4,3,4,10])
condition = V>=4
print(condition)

[False  True False  True  True]


In [22]:
V[condition]=-1
print(V)
print(type(V))


[ 2 -1  3 -1 -1]
<class 'numpy.ndarray'>


In [23]:
new_arr=np.where(condition,-1,V)
print(new_arr)

[ 2 -1  3 -1 -1]
